receivers:
  otlp:
    protocols:
      grpc:
        include_metadata: true
      http:
        include_metadata: true
        cors:
          allowed_origins:
            - http://*
            - https://*
          allowed_headers:
            - '*'
  zipkin:
  jaeger:
    protocols:
      grpc:
      thrift_binary:
      thrift_compact:
      thrift_http:

processors:
  batch:
  # attributes:
  #   actions:
  #     - key: seq
  #       action: delete # remove sensitive element

exporters:
  jaeger:
    endpoint: jaeger-all-in-one:14250
    tls:
      insecure: true
  zipkin:
    endpoint: "http://zipkin-all-in-one:9411/api/v2/spans"
  prometheus:
    endpoint: "0.0.0.0:9464" # this is weird because the exporter is actually an endpoint that must be scraped
  # logging:
  #   loglevel: debug

extensions:
  health_check:
  pprof:
  zpages:

service:
  # extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [zipkin]
      processors: [batch]

    metrics:
      receivers: [otlp]
      exporters: [prometheus]
      processors: [batch]
    # logs:
    #     receivers: [otlp]
    #     processors: [batch]
    #     exporters: [zipkin]
