global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'collector'
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
      - targets: ['0.0.0.0:8889']
      - targets: ['0.0.0.0:8888']

  - job_name: 'prometheus'
    static_configs:
    - targets: ['0.0.0.0:9090']

  # - job_name: 'otel-collector'
  #   scrape_interval: 10s
  #   static_configs:
  #     - targets: ['0.0.0.0:8889']
  #     - targets: ['0.0.0.0:8888']